dataset_name: CIFAR10
exp_depths: [1]
dummy: true

dataset:
  name: CIFAR10
  num_classes: 10
  img_channels: 3
  norm_mean: [0.4914, 0.4822, 0.4465]
  norm_std: [0.2023, 0.1994, 0.2010]
  ntrain: 500
  dummy: true

vgg:
  channels: [32, 64, 128, 128, 256, 256, 512, 512]
  is_maxpool: [true, true, false, true, false, false, true, false]

resnet:
  channels: [64, 64, 128, 128, 256, 256, 512, 512, 512]
  strides: [1, 1, 1, 2, 1, 2, 1, 2, 1]

train:
  dummy: true
  batch_size: 128
  epochs: 10
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  lr_scheduler: step
  gamma: 0.1
  niter: 1000
  milestones: [5, 10]

exp:
  exp_depths: [1]
  data_name: CIFAR10
  nin: 1
  nSplit: 16
  vgg_exp_layers: [1, 3, 5]
  resnet_exp_layers: [1, 4, 6]
  expRed: [1, 2]
  exps: ["C", "R", "1"]
  maxRan: 1.0
  miExp: false
